### ISSUE TITLE
No such PR

### ISSUE THREAD

**Issue by cyrus-za** [kt3k/update-pr-description#4]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/1845861/108689789-31c04280-7502-11eb-9eb8-bbfc1a27014f.png">

The PR does exist and I do have `github_token: ${{ secrets.GITHUB_TOKEN }}` set. Not sure why it is failing. Yes the PR does point to master

**Comment by rpbaltazar** [comment]
Can you share your workflow setup?

**Comment by mau2099** [comment]
did you find and answer? it looks like it's only triggerd on `push` events

**Comment by mau2099** [comment]
I have this workflow, but i'm getting the same error message:
``` YAML
name: CI Badges

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_body: 'some script for creating PR description from the branch diff'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: feat/form-1372-release-cimaster-4 #i've tried with default **master**
```
